name: Client CI

on:
  push:
    tags: '**'
    paths:
      - 'client/**'

  workflow_dispatch:

defaults:
  run:
    working-directory: 'client'

jobs:
  build_publish:
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Install vsce
      run: yarn global add vsce

    - name: Publish extension
      run: vsce publish
