name: CI

on:
  create:
  push: 
    branches: [ master ]
    tags: '**'
  pull_request:
    branches: [ master ]

  workflow_dispatch:

defaults:
  run:
    working-directory: 'server'

jobs:
  build_and_test_server:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl: [ '5.34', '5.32', '5.30', '5.28', '5.26' ]
        
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: shogo82148/actions-setup-perl@v1.12.2
        with:
          perl-version: ${{ matrix.perl }}
          
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: local
          key: ${{ matrix.os }}-${{ matrix.perl }}-dependencies

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cpanm --local-lib-contained local --notest --installdeps .
          echo "PERL5LIB='$PWD/local/lib/perl5:$PERL5LIB'" >> $GITHUB_ENV
          
      - name: Create Makefile
        run: perl Makefile.PL
        
      - name: Make module
        run: make
        
      - name: Run tests
        run: make test
        
      - name: Build distribution
        run: make dist
        
      - name: Archive module artifact
        uses: actions/upload-artifact@v2
        with:
          name: module-archive
          path: |
            PLS*.tar.gz
    
  publish_server:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: shogo82148/actions-setup-perl@v1.12.2
        with:
          perl-version: '5.34'
      
      - uses: actions/download-artifact@v2
        with:
          name: module-archive

      - name: Publish to CPAN
        run: cpan-upload -u mreisner -p ${{ secrets.PAUSE_PASSWORD }} PLS*.tar.gz
