name: Server CI

on:
  create:
  push:
    branches: [ master ]
    tags: '**'
    paths:
      - 'server/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'server/**'

  workflow_dispatch:

defaults:
  run:
    working-directory: 'server'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        perl: [ '5.34', '5.32', '5.30', '5.28', '5.26' ]

    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: shogo82148/actions-setup-perl@v1.12.2
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpanm
          working-directory: server

      - name: Create Makefile
        run: perl Makefile.PL

      - name: Make module
        run: make

      - name: Run tests
        run: make test

      - name: Build distribution
        run: make dist

      - name: Archive module artifact
        uses: actions/upload-artifact@v2
        with:
          name: module-archive-${{ matrix.os }}-${{ matrix.perl }}
          path: |
            server/PLS*.tar.gz

  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shogo82148/actions-setup-perl@v1.12.2
        with:
          perl-version: '5.34'

      - uses: actions/download-artifact@v2
        with:
          name: module-archive-ubuntu-latest-5.34

      - name: Publish to CPAN
        run: cpan-upload -u mreisner -p ${{ secrets.PAUSE_PASSWORD }} PLS*.tar.gz
